#!/bin/bash

CFG="$HOME/.config/eww/dashboard"

if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

run_eww() {
	eww --config $CFG open-many \
		profile \
		system \
		clock \
		uptime \
		music \
		github \
		reddit \
		twitter \
		youtube \
		weather \
		apps \
		mail \
		logout \
		sleep \
		reboot \
		poweroff \
		folders
}

run_eww
