alias dshutdown="sudo shutdown now"
alias dreboot="sudo reboot"
alias dupdate="sudo apt update"
alias dupgrade="sudo apt upgrade"
alias dinstall="sudo apt install"
alias dremove="sudo apt remove"
alias dsearch="apt search"
alias dinfo="apt show"
